#!/usr/bin/env python3
import sys
import os
import subprocess
import shlex


BUILTINS = {"echo", "type", "exit", "pwd", "cd"}


def isinpath(command):
    for path in os.environ["PATH"].split(os.pathsep):
        if not os.path.exists(path):
            continue

        for e in os.listdir(path):
            filepath = f"{path}/{e}"
            if command == e and os.access(filepath, os.X_OK):
                return filepath

def run_program(command, args):
    process = subprocess.Popen(
        [command, *args],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True, bufsize=1  # Line-buffered
    )

    # Read stdout in real-time as lines arrive
    while True:
        output = process.stdout.readline()

        if not output and process.poll() is not None:
            break

        if output:
            print(output, end='')
            sys.stdout.flush()  # print to the screen immediately

    stderr = process.stderr.read()
    if stderr:
        print(stderr, end='', file=sys.stderr)



def main():
    while True:
        sys.stdout.write("$ ")

        # extract command and arguments
        # shlex.split handles the quoting
        user_input = shlex.split(input())
        command = user_input[0]
        args = user_input[1:]

        # handle built-ins
        if command == "exit":
            break
        if command == "echo":
            print(*args)
        elif command == "pwd":
            print(os.getcwd())
        elif command == "cd":
            path = args[0]
            if path.startswith('~'):
                path = path.replace('~', os.environ["HOME"])
            if os.path.exists(path):
                os.chdir(path)
            else:
                print(f"{command}: {path}: No such file or directory")
        elif command == "type":
            for arg in args:
                if arg in BUILTINS:
                    print(f"{arg} is a shell builtin")
                    continue

                filepath = isinpath(arg)
                if filepath:
                    print(f"{arg} is {filepath}")
                else:
                    print(f"{arg}: not found")

        if command in BUILTINS: continue

        # handle executables
        filepath = isinpath(command)
        if filepath and os.access(filepath, os.X_OK):
            run_program(command, args)
        elif os.access(command, os.X_OK):
            run_program(command, args)
        else:
            print(f"{command}: command not found")


if __name__ == "__main__": main()
